name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH=$PATH:/usr/bin:/usr/local/bin
            cd ~/Assessment-CSV-Editor-Backend
            git pull origin main

            if ! command -v pnpm &> /dev/null
            then
              echo "Installing pnpm..."
              npm install -g pnpm
            fi

            if ! command -v pm2 &> /dev/null
            then
              echo "Installing pm2..."
              npm install -g pm2
            fi

            pnpm install
            pnpm build
            pm2 restart server
